'use strict';
const sections=[['profil','Profil','◇'],['experience','Alternance','⌘'],['projets','Projets','✧'],['parcours','Formations','⌁'],['stack','Compétences','⟐'],['langues','Langues','◎']];
const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tags=xs=>`<div class="tags">${xs.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`;
const missions=[
{title:'Automatisation & CI/CD',sub:'Renouvellement des licences XL Deploy',tools:['GitHub Actions','Ansible','XL Deploy'],context:'XL Deploy est un outil de déploiement applicatif. Le renouvellement des licences fait partie de sa maintenance opérationnelle.',actions:['Automatisation du renouvellement des licences avec GitHub Actions et Ansible.','Intégration d’une sauvegarde avant intervention.','Prise en compte du rollback pour pouvoir revenir à l’état précédent.'],stages:[['Préparer','Préparer le renouvellement et la sauvegarde de l’existant.'],['Automatiser','Orchestrer les actions avec GitHub Actions et Ansible.'],['Revenir','Prévoir le retour arrière avec le backup et le rollback.']]},
{title:'Platform Engineering',sub:'Migration Apache Airflow 2.x → 3.x',tools:['Apache Airflow','Python','Ruff'],context:'Apache Airflow orchestre des workflows décrits sous forme de DAGs. Une migration concerne les instances comme le code exécuté.',actions:['Migration d’instances Apache Airflow de la version 2.x vers 3.x et de leurs DAGs.','Adaptation du code aux évolutions de la plateforme.','Troubleshooting post-migration : analyse des erreurs et du chargement des DAGs.'],stages:[['Adapter','Faire évoluer le code des DAGs et vérifier sa compatibilité.'],['Migrer','Migrer les instances et leurs workflows vers Airflow 3.x.'],['Diagnostiquer','Analyser les erreurs observées après la migration.']]},
{title:'Développement Python',sub:'Évolution de la CLI interne unicli',tools:['Python','Click','API ITSM','Git'],context:'unicli est une interface en ligne de commande interne qui interagit avec l’ITSM via API pour accompagner la gestion des changements.',actions:['Ajout de paramètres pour adapter les demandes de changement.','Ajout de validations, notamment sur les dates et les entrées.','Amélioration du code et de la gestion des changements via API.'],stages:[['Saisir','Recevoir les paramètres de la demande en ligne de commande.'],['Valider','Contrôler les entrées et la cohérence des dates.'],['Transmettre','Construire la demande et interagir avec l’ITSM via API.']]},
{title:'Reliability',sub:'Exercices de Backup & Restore PostgreSQL',tools:['PostgreSQL','Backup & Restore','Procédures'],context:'Une sauvegarde n’est utile que si sa restauration fonctionne. Ces exercices permettent de confronter les procédures à leur exécution.',actions:['Réalisation d’exercices de sauvegarde et de restauration PostgreSQL.','Validation des procédures de restauration.'],stages:[['Sauvegarder','Réaliser l’exercice de backup PostgreSQL.'],['Restaurer','Exécuter les étapes de restauration.'],['Valider','Vérifier les procédures à l’issue de l’exercice.']]},
{title:'Observabilité',sub:'Upgrade de SG Monitoring Realms',tools:['SG Monitoring Realms','Monitoring'],context:'Le maintien des outils de supervision accompagne la fiabilité de l’environnement technique.',actions:['Participation à l’upgrade de SG Monitoring Realms.','Réalisation de contrôles après la mise à niveau.'],stages:[['Mettre à niveau','Effectuer l’upgrade de SG Monitoring Realms.'],['Contrôler','Réaliser les vérifications post-upgrade.']]},
{title:'Sécurité & conformité',sub:'Contrôles CG25 / CG27 sur plusieurs plateformes',tools:['Comptes techniques','Vault','Authentification','Conformité'],context:'La supervision permanente vise à vérifier la conformité des comptes techniques et des pratiques d’authentification.',actions:['Contrôle des comptes techniques et de leur ownership.','Vérification de la rotation des credentials et du stockage des secrets en vault.','Revue des méthodes d’authentification et formalisation des constats de conformité.'],stages:[['Identifier','Vérifier le propriétaire et l’usage des comptes techniques.'],['Contrôler','Revoir la rotation, le stockage et l’authentification.'],['Qualifier','Déterminer la conformité des éléments examinés.']]},
{title:'Software Engineering',sub:'Maintenance évolutive de DUAR',tools:['DUAR','Maintenance évolutive','Qualité du code'],context:'DUAR est un outil interne sur lequel je contribue à la maintenance évolutive.',actions:['Maintenance évolutive de l’outil.','Amélioration du code existant.'],stages:[['Faire évoluer','Apporter les évolutions nécessaires à l’outil.'],['Améliorer','Intervenir sur la qualité du code existant.']]}
];
const projects=[
{title:'Licences XL Deploy',kind:'Alternance',desc:'Un renouvellement automatisé, avec sauvegarde et retour arrière.',mission:0,symbol:'⌘'},
{title:'Apache Airflow 3',kind:'Alternance',desc:'Faire évoluer une plateforme d’orchestration et ses DAGs.',mission:1,symbol:'⌁'},
{title:'unicli · Python & ITSM',kind:'Alternance',desc:'Une CLI interne pour accompagner la gestion des changements.',mission:2,symbol:'›_'},
{title:'Atlas Helpdesk',kind:'Master · projet collectif',desc:'Une infrastructure helpdesk avec segmentation, supervision et PRA.',symbol:'⟐',tools:['GLPI','ESXi / Proxmox','Nginx / TLS','Zabbix'],url:'https://github.com/nazym1234/Atlas-helpdesk-project',context:'Projet pédagogique Helpdesk Atlas, réalisé dans le cadre du Master 1 IRS. L’infrastructure repose sur GLPI dans un environnement virtualisé.',actions:['Projet d’infrastructure segmentée en zones DMZ, LAN et management.','Reverse proxy Nginx avec TLS et supervision Zabbix.','Participation à l’analyse des risques ; un plan de reprise d’activité est documenté dans le projet.'],stages:[['Accès','Reverse proxy Nginx avec TLS.'],['Service','Helpdesk GLPI sur environnement virtualisé.'],['Continuité','Supervision Zabbix et PRA documenté.']]},
{title:'Analyseur de trafic réseau',kind:'Projet de développement',desc:'Capturer et décoder des paquets réseau en Rust.',symbol:'◎',tools:['Rust','pnet','TCP/IP','DNS / HTTP'],context:'Un sniffer est un outil d’observation du trafic réseau. Ce projet décrit dans mon CV utilise Rust et la bibliothèque pnet.',actions:['Développement d’un outil de capture et d’analyse du trafic en temps réel.','Décodage des adresses IP, des ports et d’informations DNS et HTTP.'],stages:[['Capturer','Observer les paquets à l’aide de pnet.'],['Décoder','Extraire les informations des protocoles réseau.'],['Analyser','Lire les adresses, les ports et le trafic applicatif.']]},
{title:'Jeu 3D en réseau local',kind:'Projet de développement',desc:'Un jeu multijoueur Unity avec un modèle client-serveur.',symbol:'✧',tools:['Unity','C#','TCP','UDP'],context:'Projet de jeu vidéo 3D en multijoueur local, présenté dans mon CV. Le modèle client-serveur permet d’organiser les échanges entre joueurs.',actions:['Développement avec Unity et C#.','Gestion des connexions avec TCP.','Synchronisation des actions des joueurs en temps réel avec UDP.'],stages:[['Connecter','Établir les connexions entre les clients et le serveur.'],['Synchroniser','Échanger les actions des joueurs via UDP.'],['Jouer','Maintenir la cohérence de la partie en réseau local.']]},
{title:'Flappy OCaml',kind:'Projet public',desc:'Un jeu pour explorer la physique, les collisions et la programmation fonctionnelle.',symbol:'⌁',tools:['OCaml','Boucle de jeu','Collisions'],url:'https://github.com/nazym1234/flappy-bird-en-ocaml',context:'Une implémentation simplifiée de Flappy Bird en OCaml avec une physique rudimentaire et un affichage textuel.',actions:['Mise à jour de la physique et de l’affichage dans une boucle de jeu.','Gestion de la gravité, des sauts et des collisions.','Génération aléatoire d’obstacles et système de score.'],stages:[['Entrée','Contrôler le saut et le déplacement.'],['Physique','Appliquer la gravité et détecter les collisions.'],['Affichage','Mettre à jour le jeu et le score.']]},
{title:'Grammaires & compilation',kind:'Projet universitaire',desc:'Explorer les formes normales et la génération de mots.',symbol:'{ }',tools:['Grammaires algébriques','Chomsky','Greibach'],url:'https://github.com/nazym1234/Compilation',context:'Projet universitaire consacré aux transformations de grammaires algébriques et à la génération de mots. Le dépôt présente le code et le sujet du projet.',actions:['Travail sur la représentation et la lecture de grammaires.','Étude des transformations vers les formes normales de Chomsky et de Greibach.','Travail sur la génération de mots jusqu’à une longueur donnée.'],stages:[['Lire','Représenter une grammaire à partir d’un fichier.'],['Transformer','Étudier ses formes normales.'],['Générer','Produire les mots du langage dans une limite de longueur.']]}
];
const accordion=(m,i)=>`<details class="mission"><summary><span class="mission-number">0${i+1}</span><span><strong>${m.title}</strong><small>${m.sub}</small></span><span class="plus" aria-hidden="true">+</span></summary><div class="mission-body"><p>${m.context}</p><h4>Mon intervention</h4><ul>${m.actions.map(a=>`<li>${a}</li>`).join('')}</ul>${tags(m.tools)}<button class="text-link" data-mission="${i}">Voir le déroulé interactif ↗</button></div></details>`;
const views={
profil:()=>`<div class="two-col"><div><p class="eyebrow">01 · MON PROFIL</p><h2>La curiosité comme<br><em>point de départ.</em></h2><p>Étudiant en réseaux et systèmes à l’UVSQ – Paris-Saclay, je développe mon expérience de Site Reliability Engineer en alternance à la Société Générale.</p><p class="muted">J’aime comprendre les infrastructures, automatiser les opérations répétitives et améliorer le code. Mon parcours relie cloud, exploitation et cybersécurité.</p>${tags(['SRE / DevOps','Cloud','Cybersécurité'])}<a class="text-link spaced" href="https://github.com/nazym1234" target="_blank" rel="noopener noreferrer">Parcourir mon GitHub ↗</a></div><div class="principles">${[['01','Automatiser','GitHub Actions, Ansible et Python au service des opérations.'],['02','Fiabiliser','Migration de plateformes, restauration et contrôles après intervention.'],['03','Sécuriser','Conformité des comptes, gestion des secrets et méthodes d’authentification.']].map(x=>`<article class="card principle"><span>${x[0]}</span><div><h3>${x[1]}</h3><p>${x[2]}</p></div></article>`).join('')}<p class="small-note">Au-delà du code : jeux vidéo, tir à l’arc, dessin et cinéma.</p></div></div>`,
experience:()=>`<div class="two-col"><div><p class="eyebrow">02 · L’EXPÉRIENCE TERRAIN</p><h2>Site Reliability<br><em>Engineer.</em></h2><p class="gold">Société Générale · Alternance</p><p class="meta">Septembre 2025 — 2027 · La Défense</p><p>Automatisation, plateformes, fiabilité et sécurité : sept domaines d’intervention au sein de DDS Socle & Reliability Engineering.</p>${tags(['GitHub Actions','Ansible','Python','Airflow','PostgreSQL'])}<details class="team"><summary>L’équipe & notre façon de travailler <span>+</span></summary><div><h3>DDS Socle & Reliability Engineering</h3><p>Une équipe internationale répartie entre Paris, Bangalore et Montréal, autour des socles techniques et de la fiabilité des services.</p><h4>Agile & Jira</h4><p>J’utilise Jira dans le cadre de notre méthode Agile pour suivre les tâches, partager l’avancement et coordonner les interventions avec l’équipe.</p><p class="small-note">Rythme d’alternance : une semaine de cours, trois semaines en entreprise.</p>${tags(['Jira','Agile','Collaboration internationale'])}</div></details></div><div class="missions"><p class="small-note">Ouvrez une mission pour découvrir les outils et mon intervention.</p>${missions.map(accordion).join('')}</div></div>`,
projets:()=>`<div class="heading-row"><div><p class="eyebrow">03 · LES RÉALISATIONS</p><h2>De l’idée<br><em>à la pratique.</em></h2></div><a class="primary secondary" href="https://github.com/nazym1234" target="_blank" rel="noopener noreferrer">Tous mes dépôts GitHub ↗</a></div><p class="muted">Projets d’alternance, travaux universitaires et expérimentations personnelles.</p><div class="project-grid">${projects.map((p,i)=>`<article class="project card"><div class="project-head"><span class="project-symbol">${p.symbol}</span><span class="meta">${p.kind}</span></div><h3>${p.title}</h3><p>${p.desc}</p>${tags(p.tools||missions[p.mission].tools)}<button class="explore-project" data-project="${i}">Explorer le projet <span>↗</span></button></article>`).join('')}</div>`,
parcours:()=>`<div class="two-col"><div><p class="eyebrow">04 · ÉTUDES & FORMATIONS</p><h2>Apprendre.<br><em>Puis aller plus loin.</em></h2><div class="timeline">${[
['2025 — 2027','Master · Réseaux et systèmes','UVSQ – Université Paris-Saclay','M1 Ingénierie des Réseaux et des Systèmes en alternance, avec une orientation vers la cybersécurité en M2.'],
['2024 — 2025','Licence 3 Informatique','UVSQ – Université Paris-Saclay · Versailles','Algorithmique avancée, réseaux, systèmes, bases de données et cybersécurité.'],
['2023 — 2024','Licence 2 Informatique','Université Paris-Est Créteil · UPEC','Programmation fonctionnelle, cryptographie, réseaux, systèmes et développement web.'],
['2022 — 2023','Première année de prépa intégrée','EPITA · Le Kremlin-Bicêtre','Architecture des ordinateurs, programmation, mathématiques, Linux et fondamentaux de la sécurité.']].map(x=>`<article><span class="meta">${x[0]}</span><h3>${x[1]}</h3><p class="gold">${x[2]}</p><p>${x[3]}</p></article>`).join('')}</div></div><div><h3 class="cert-heading">Formations & certifications</h3><div class="certs">${[
['✓','CCNA 1 & 2','Modules Cisco Networking Academy','Obtenus','done'],
['◷','Terraform Associate','Infrastructure as Code · HashiCorp','En préparation','progress'],
['◷','KCNA','Kubernetes and Cloud Native Associate','En préparation','progress'],
['◇','Azure Fundamentals · AZ-900','Fondamentaux du cloud Microsoft Azure','Objectif à venir','planned']].map(c=>`<article class="cert card"><span class="cert-icon">${c[0]}</span><div><h3>${c[1]}</h3><p>${c[2]}</p><span class="badge ${c[4]}">${c[3]}</span></div></article>`).join('')}</div><p class="small-note">CCNA 1 et 2 désignent les modules de formation suivis ; ils sont distincts de l’examen de certification CCNA complet.</p></div></div>`,
stack:()=>`<p class="eyebrow">05 · COMPÉTENCES & OUTILS</p><h2>Une boîte à outils.<br><em>Plusieurs terrains.</em></h2><p class="muted">Des technologies mobilisées en alternance, en formation et dans mes projets.</p><div class="stack-grid">${[
['⌘','Automatisation & CI/CD',['Ansible','GitHub Actions','GitLab CI/CD','Jenkins','XL Deploy','Git']],
['⟐','Cloud & plateformes',['AWS','Azure','Apache Airflow','Docker','Kubernetes','Argo CD','Terraform (en cours)']],
['◎','Fiabilité & observabilité',['PostgreSQL','Backup & Restore','SG Monitoring Realms','Prometheus','Grafana','Jaeger','Zabbix']],
['›_','Programmation & scripting',['Python','PowerShell','Bash','C','C#','Java','Rust','OCaml','Lua','R','SQL']],
['⌁','Web & données',['HTML','CSS','JavaScript','PHP','Laravel','SQL / PL-SQL','PostgreSQL']],
['◇','Réseaux & sécurité',['Linux','Packet Tracer','Wireshark','Nmap','Kali Linux','Nikto','John the Ripper','Secrets en vault']],
['✧','Virtualisation & projets',['VMware','VirtualBox','ESXi / Proxmox','Nginx','GLPI','Unity']],
['≋','Organisation & collaboration',['Jira','Méthode Agile','Trello','GitHub / GitLab','Documentation','LaTeX']]
].map(x=>`<article class="card stack-card"><span class="stack-symbol">${x[0]}</span><h3>${x[1]}</h3>${tags(x[2])}</article>`).join('')}</div>`,
langues:()=>`<div class="two-col"><div><p class="eyebrow">06 · LANGUES</p><h2>Comprendre.<br>Échanger.<br><em>Collaborer.</em></h2><p class="muted">Les langues accompagnent mon parcours d’études et mon travail dans une équipe internationale.</p></div><div class="languages">${[['FR','Français','Langue maternelle','Natif'],['AR','Arabe','Langue maternelle','Natif'],['EN','Anglais','TOEFL · 94 / 120','Avancé'],['ES','Espagnol','Niveau intermédiaire','B1']].map(x=>`<article class="language card"><span>${x[0]}</span><div><h3>${x[1]}</h3><p>${x[2]}</p></div><strong>${x[3]}</strong></article>`).join('')}</div></div>`
};
let current=0,rotation=0,activeProject=null,audioContext=null,scrollTimer=null;
const reducedQuery=window.matchMedia('(prefers-reduced-motion: reduce)');
const readPref=(key,fallback)=>{try{const v=localStorage.getItem(key);return v===null?fallback:v==='true';}catch{return fallback;}};
let soundEnabled=readPref('nazym-sound',true),motionEnabled=readPref('nazym-motion',!reducedQuery.matches);
function savePref(k,v){try{localStorage.setItem(k,String(v));}catch{}}
function syncSettings(){document.body.classList.toggle('reduce-motion',!motionEnabled);document.body.classList.toggle('force-motion',motionEnabled);$('#sound').setAttribute('aria-pressed',String(soundEnabled));$('#sound').innerHTML=`${soundEnabled?'♫':'♪'} <span>Sons ${soundEnabled?'activés':'coupés'}</span>`;$('#sound').title=soundEnabled?'Désactiver les sons':'Activer les sons';$('#motion').setAttribute('aria-pressed',String(motionEnabled));$('#motion').innerHTML=`✧ <span>${motionEnabled?'Animations':'Mouvement réduit'}</span>`;$('#motion').title=motionEnabled?'Réduire les animations':'Activer les animations';}
async function chime(){if(!soundEnabled)return;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;audioContext??=new Audio();if(audioContext.state==='suspended')await audioContext.resume();const t=audioContext.currentTime;[659.25,987.77].forEach((frequency,i)=>{const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.type='sine';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(0,t+i*.035);gain.gain.linearRampToValueAtTime(.025,t+i*.035+.012);gain.gain.exponentialRampToValueAtTime(.0001,t+i*.035+.20);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start(t+i*.035);oscillator.stop(t+i*.035+.22);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();};});}catch{/* Audio is optional; navigation always remains available. */}}
$('#wheel').innerHTML=sections.map((s,i)=>`<div class="spoke" style="--position:${i*60}deg"><button data-section="${s[0]}" class="orb-node" aria-label="${s[1]}" style="--unposition:${-i*60}deg"><span class="orb-symbol">${s[2]}</span><span>${s[1]}</span></button></div>`).join('');
$('#tabs').innerHTML=sections.map((s,i)=>`<button data-section="${s[0]}"><small>0${i+1}</small> ${s[1]}</button>`).join('');
function renderSection(key,updateHash=true){const index=sections.findIndex(x=>x[0]===key);if(index<0)return;let delta=index-current;if(delta>3)delta-=6;if(delta<-3)delta+=6;rotation-=delta*60;current=index;$('#wheel').style.setProperty('--rotation',rotation+'deg');$('#wheel').style.setProperty('--counter',-rotation+'deg');$('#core-number').textContent='CHAPITRE 0'+(index+1);$('#core-label').textContent=sections[index][1];$('#core-symbol').textContent=sections[index][2];$('#count').textContent=`0${index+1} / 06`;document.querySelectorAll('[data-section]').forEach(b=>{const active=b.dataset.section===key;b.classList.toggle('active',active);active?b.setAttribute('aria-current','true'):b.removeAttribute('aria-current');});$('#panel').innerHTML=views[key]();$('#panel').classList.remove('arrive');void $('#panel').offsetWidth;$('#panel').classList.add('arrive');if(updateHash)history.replaceState(null,'','#'+key);}
const dialog=$('#project-dialog');
function showProject(p){activeProject=p;const d=p.mission===undefined?p:{...missions[p.mission],title:p.title,kind:'Alternance · Société Générale'};activeProject=d;$('#project-content').innerHTML=`<p class="meta">${esc(d.kind||'Alternance · Société Générale')}</p><h2 id="project-title">${esc(d.title)}</h2>${tags(d.tools)}<h3>Le contexte & les outils</h3><p>${esc(d.context)}</p><h3>Mon travail</h3><ul>${d.actions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="project-flow"><p class="eyebrow">LE DÉROULÉ · CLIQUEZ SUR UNE ÉTAPE</p><div class="flow-buttons">${d.stages.map((s,i)=>`<button data-step="${i}" aria-pressed="${i===0}" class="${i===0?'active':''}"><small>0${i+1}</small>${esc(s[0])}</button>`).join('')}</div><p id="step-detail" aria-live="polite">${esc(d.stages[0][1])}</p></div>${d.url?`<a class="primary" href="${d.url}" target="_blank" rel="noopener noreferrer">Voir le dépôt GitHub ↗</a>`:`<p class="small-note">${d.kind?.includes('Alternance')?'Projet interne : présentation de mes contributions, sans publication du code de l’entreprise.':'Projet présenté dans mon parcours. Aucun dépôt public associé à cette fiche.'}</p>`}`;dialog.showModal();document.body.classList.add('modal-open');}
dialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));
$('#close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
document.addEventListener('click',e=>{const button=e.target.closest('button,a,summary');if(!button)return;if(button.id==='sound'){soundEnabled=!soundEnabled;savePref('nazym-sound',soundEnabled);syncSettings();if(soundEnabled)chime();return;}chime();if(button.id==='motion'){motionEnabled=!motionEnabled;savePref('nazym-motion',motionEnabled);syncSettings();}if(button.dataset.section){clearTimeout(scrollTimer);renderSection(button.dataset.section);if(button.closest('#wheel'))scrollTimer=setTimeout(()=>$('#explorer').scrollIntoView({behavior:motionEnabled?'smooth':'instant'}),motionEnabled?1000:0);if(button.closest('#tabs'))$('#panel').focus({preventScroll:true});}if(button.dataset.project!==undefined)showProject(projects[Number(button.dataset.project)]);if(button.dataset.mission!==undefined){const i=Number(button.dataset.mission);showProject({...missions[i],kind:'Alternance · Société Générale'});}if(button.dataset.step!==undefined&&activeProject){const i=Number(button.dataset.step);$('#step-detail').textContent=activeProject.stages[i][1];document.querySelectorAll('[data-step]').forEach(b=>{const on=Number(b.dataset.step)===i;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});}});
$('#previous').addEventListener('click',()=>renderSection(sections[(current+5)%6][0]));$('#next').addEventListener('click',()=>renderSection(sections[(current+1)%6][0]));
$('#tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const i=e.key==='Home'?0:e.key==='End'?5:(current+(e.key==='ArrowRight'?1:5))%6;renderSection(sections[i][0]);$('#tabs').querySelectorAll('button')[i].focus();chime();});
window.addEventListener('hashchange',()=>{const key=location.hash.slice(1);if(views[key])renderSection(key,false);});
syncSettings();renderSection(views[location.hash.slice(1)]?location.hash.slice(1):'profil',false);
